# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accueil_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 10, 261, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 70, 256, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(480, 70, 256, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 20, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(510, 20, 241, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(380, 70, 20, 481))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.list_visiteur = QtWidgets.QPushButton(self.centralwidget)
        self.list_visiteur.setGeometry(QtCore.QRect(110, 120, 131, 61))
        self.list_visiteur.setObjectName("list_visiteur")
        self.list_guest = QtWidgets.QPushButton(self.centralwidget)
        self.list_guest.setGeometry(QtCore.QRect(110, 190, 131, 61))
        self.list_guest.setObjectName("list_guest")
        self.list_seller = QtWidgets.QPushButton(self.centralwidget)
        self.list_seller.setGeometry(QtCore.QRect(110, 260, 131, 61))
        self.list_seller.setObjectName("list_seller")
        self.list_stand = QtWidgets.QPushButton(self.centralwidget)
        self.list_stand.setGeometry(QtCore.QRect(110, 330, 131, 61))
        self.list_stand.setObjectName("list_stand")
        self.list_recette = QtWidgets.QPushButton(self.centralwidget)
        self.list_recette.setGeometry(QtCore.QRect(110, 400, 131, 61))
        self.list_recette.setObjectName("list_recette")
        self.list_schedule = QtWidgets.QPushButton(self.centralwidget)
        self.list_schedule.setGeometry(QtCore.QRect(110, 470, 131, 61))
        self.list_schedule.setObjectName("list_schedule")
        self.modify_schedule = QtWidgets.QPushButton(self.centralwidget)
        self.modify_schedule.setGeometry(QtCore.QRect(540, 120, 131, 61))
        self.modify_schedule.setObjectName("modify_schedule")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdministration = QtWidgets.QMenu(self.menubar)
        self.menuAdministration.setObjectName("menuAdministration")
       #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
       #MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAdministration.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Administration</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Affichage</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Gestion</span></p></body></html>"))
        self.list_visiteur.setText(_translate("MainWindow", "Afficher les visiteurs"))
        self.list_guest.setText(_translate("MainWindow", "Afficher les invités"))
        self.list_seller.setText(_translate("MainWindow", "Afficher les vendeurs"))
        self.list_stand.setText(_translate("MainWindow", "Afficher les stands"))
        self.list_recette.setText(_translate("MainWindow", "Afficher la recette"))
        self.list_schedule.setText(_translate("MainWindow", "Afficher les horaires"))
        self.modify_schedule.setText(_translate("MainWindow", "Gérer les horaires"))
        self.menuAdministration.setTitle(_translate("MainWindow", "Administration"))
