# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 399)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 256, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.submit_data = QtWidgets.QPushButton(Form)
        self.submit_data.setGeometry(QtCore.QRect(360, 140, 93, 28))
        self.submit_data.setObjectName("submit_data")
        self.cancel_data = QtWidgets.QPushButton(Form)
        self.cancel_data.setGeometry(QtCore.QRect(360, 180, 93, 28))
        self.cancel_data.setObjectName("cancel_data")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.submit_data.setText(_translate("Form", "Valider"))
        self.cancel_data.setText(_translate("Form", "Annuler"))
