# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 288)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 240, 321, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 55, 16))
        self.label_2.setObjectName("label_2")


        self.inscription = QtWidgets.QPushButton(self.centralwidget)
        self.inscription.setGeometry(QtCore.QRect(150, 250, 93, 28))
        self.inscription.setObjectName("inscription")


        self.valider_connection = QtWidgets.QPushButton(self.centralwidget)
        self.valider_connection.setGeometry(QtCore.QRect(160, 200, 71, 28))
        self.valider_connection.setObjectName("valider_connection")


        self.mdp_input = QtWidgets.QLineEdit(self.centralwidget)
        self.mdp_input.setGeometry(QtCore.QRect(140, 160, 113, 22))
        self.mdp_input.setObjectName("mdp_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mail_input = QtWidgets.QLineEdit(self.centralwidget)
        self.mail_input.setGeometry(QtCore.QRect(140, 110, 113, 22))
        self.mail_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mail_input.setObjectName("mail_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 140, 55, 16))
        self.label_3.setObjectName("label_3")
       # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "e-mail"))
        self.inscription.setText(_translate("MainWindow", "inscription"))
        self.valider_connection.setText(_translate("MainWindow", "valider"))
        self.label.setText(_translate("MainWindow", "Connection"))
        self.label_3.setText(_translate("MainWindow", "mdp"))
