# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guest_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(428, 343)
        self.deco_button = QtWidgets.QPushButton(Form)
        self.deco_button.setGeometry(QtCore.QRect(160, 260, 91, 24))
        self.deco_button.setObjectName("deco_button")
        self.input_text = QtWidgets.QTextBrowser(Form)
        self.input_text.setGeometry(QtCore.QRect(90, 70, 241, 171))
        self.input_text.setObjectName("input_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guest"))
        self.deco_button.setText(_translate("Form", "Déconnection"))
        self.label.setText(_translate("Form", "Rappel "))
