# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guest_inscription.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(499, 258)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(140, 40, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.precedent_button = QtWidgets.QPushButton(Form)
        self.precedent_button.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.precedent_button.setFlat(False)
        self.precedent_button.setObjectName("precedent_button")
        self.time_visite = QtWidgets.QTimeEdit(Form)
        self.time_visite.setEnabled(True)
        self.time_visite.setGeometry(QtCore.QRect(50, 110, 118, 22))
        self.time_visite.setObjectName("time_visite")
        self.visite_choice = QtWidgets.QComboBox(Form)
        self.visite_choice.setGeometry(QtCore.QRect(200, 110, 241, 22))
        self.visite_choice.setEditable(False)
        self.visite_choice.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.visite_choice.setDuplicatesEnabled(False)
        self.visite_choice.setModelColumn(0)
        self.visite_choice.setObjectName("visite_choice")
        self.visite_choice.addItem("")
        self.visite_choice.addItem("")
        self.visite_choice.addItem("")
        self.visite_choice.addItem("")
        self.visite_choice.addItem("")
        self.submit_guest = QtWidgets.QPushButton(Form)
        self.submit_guest.setGeometry(QtCore.QRect(360, 190, 75, 23))
        self.submit_guest.setObjectName("submit_guest")

        self.retranslateUi(Form)
        self.visite_choice.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guest"))
        self.label.setText(_translate("Form", "Guest"))
        self.precedent_button.setText(_translate("Form", "Précédent"))
        self.visite_choice.setCurrentText(_translate("Form", "default"))
        self.visite_choice.setItemText(0, _translate("Form", "default"))
        self.visite_choice.setItemText(1, _translate("Form", "lieu 1"))
        self.visite_choice.setItemText(2, _translate("Form", "lieu 2"))
        self.visite_choice.setItemText(3, _translate("Form", "lieu 3"))
        self.visite_choice.setItemText(4, _translate("Form", "lieu 4"))
        self.submit_guest.setText(_translate("Form", "Valider"))
