# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Schedule):
        Schedule.setObjectName("Schedule")
        Schedule.resize(765, 409)
        self.calendarWidget = QtWidgets.QCalendarWidget(Schedule)
        self.calendarWidget.setGeometry(QtCore.QRect(340, 60, 411, 311))
        self.calendarWidget.setObjectName("calendarWidget")
        self.textBrowser = QtWidgets.QTextBrowser(Schedule)
        self.textBrowser.setGeometry(QtCore.QRect(280, 10, 201, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(Schedule)
        self.line.setGeometry(QtCore.QRect(0, 20, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Schedule)
        self.line_2.setGeometry(QtCore.QRect(520, 20, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dateEdit = QtWidgets.QDateEdit(Schedule)
        self.dateEdit.setGeometry(QtCore.QRect(210, 80, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Schedule)
        self.dateEdit_2.setGeometry(QtCore.QRect(210, 130, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(Schedule)
        self.dateEdit_3.setGeometry(QtCore.QRect(210, 180, 110, 22))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.dateEdit_4 = QtWidgets.QDateEdit(Schedule)
        self.dateEdit_4.setGeometry(QtCore.QRect(210, 230, 110, 22))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.dateEdit_6 = QtWidgets.QDateEdit(Schedule)
        self.dateEdit_6.setGeometry(QtCore.QRect(210, 330, 110, 22))
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.dateEdit_8 = QtWidgets.QDateEdit(Schedule)
        self.dateEdit_8.setGeometry(QtCore.QRect(210, 280, 110, 22))
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.timeEdit = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit.setGeometry(QtCore.QRect(30, 80, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit_2.setGeometry(QtCore.QRect(30, 130, 118, 22))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_3 = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit_3.setGeometry(QtCore.QRect(30, 230, 118, 22))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit_4.setGeometry(QtCore.QRect(30, 180, 118, 22))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.timeEdit_5 = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit_5.setGeometry(QtCore.QRect(30, 330, 118, 22))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.timeEdit_6 = QtWidgets.QTimeEdit(Schedule)
        self.timeEdit_6.setGeometry(QtCore.QRect(30, 280, 118, 22))
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.pushButton = QtWidgets.QPushButton(Schedule)
        self.pushButton.setGeometry(QtCore.QRect(30, 370, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Schedule)
        QtCore.QMetaObject.connectSlotsByName(Schedule)

    def retranslateUi(self, Schedule):
        _translate = QtCore.QCoreApplication.translate
        Schedule.setWindowTitle(_translate("Schedule", "Form"))
        self.textBrowser.setHtml(_translate("Schedule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Les Horaires</span></p></body></html>"))
        self.pushButton.setText(_translate("Schedule", "Précédent"))
