# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sokaradian\skrd\ESIEA\GLPOO\TP_GLPOO\view\Visiteur\billetterie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 324)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_billets = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_billets.setGeometry(QtCore.QRect(110, 110, 211, 22))
        self.comboBox_billets.setObjectName("comboBox_billets")
        self.comboBox_billets.addItem("")
        self.comboBox_billets.addItem("")
        self.comboBox_billets.addItem("")
        self.comboBox_billets.addItem("")
        self.valid_ticket = QtWidgets.QPushButton(self.centralwidget)
        self.valid_ticket.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.valid_ticket.setObjectName("valid_ticket")
        self.title_display = QtWidgets.QLabel(self.centralwidget)
        self.title_display.setGeometry(QtCore.QRect(140, 60, 141, 16))
        self.title_display.setObjectName("title_display")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 21))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_billets.setItemText(0, _translate("MainWindow", "-18 guest & stands - 5€"))
        self.comboBox_billets.setItemText(1, _translate("MainWindow", "guest - 7€"))
        self.comboBox_billets.setItemText(2, _translate("MainWindow", "stand - 5€"))
        self.comboBox_billets.setItemText(3, _translate("MainWindow", "guest & stands - 10€"))
        self.valid_ticket.setText(_translate("MainWindow", "Valider"))
        self.title_display.setText(_translate("MainWindow", "Selectionnez votre billet"))
