# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sokaradian\skrd\ESIEA\GLPOO\TP_GLPOO\list_seller_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, visiteur_controller):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_guest_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_guest_widget.setGeometry(QtCore.QRect(80, 50, 201, 192))
        self.list_guest_widget.setObjectName("list_guest_widget")

        self.listlayout = QtWidgets.QGridLayout()
        self.listwidget = QtWidgets.QListWidget()
        print("guest - half setup")
        self.member_mapping = {}
        self.layout = QtWidgets.QHBoxLayout()

        self.list(visiteur_controller)


        print("after list")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def list(self, visiteur_controller):
        print("call")
        index = 0
        print(visiteur_controller.list_guests())
        for member in visiteur_controller.list_guests():
            print(member['id_personne'])
            nom = visiteur_controller.get_guests(member['id_personne'])
            self.list_guest_widget.insertItem(index, "* %s" % (
                nom['firstname']))
            print("ici")
            self.member_mapping[index] = member
            index += 1


        self.list_guest_widget.resize(self.list_guest_widget.sizeHint())
        self.list_guest_widget.move(0, 60)
        self.listlayout.addWidget(self.listwidget)
        self.layout.addLayout(self.listlayout)
        print("on en sort")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

