# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sokaradian\skrd\ESIEA\GLPOO\TP_GLPOO\list_seller_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow, visiteur_controller, seller_id):
        self.visiteur_controller = visiteur_controller
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_article_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_article_widget.setGeometry(QtCore.QRect(80, 50, 201, 192))
        self.list_article_widget.setObjectName("list_article_widget")

        self.valid_article_button = QtWidgets.QPushButton(self.centralwidget)
        self.valid_article_button.setGeometry(QtCore.QRect(130, 270, 91, 23))
        self.valid_article_button.setObjectName("valid_article_button")
        self.valid_article_button.clicked.connect(self.add)

        self.listlayout = QtWidgets.QGridLayout()
        self.listwidget = QtWidgets.QListWidget()
        self.member_mapping = []
        self.layout = QtWidgets.QHBoxLayout()

        self.list(seller_id)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def list(self, seller_id):
        index = 0
        for article in self.visiteur_controller.list_article_from_seller(seller_id):
            print(article['id_seller'])
            if seller_id == article['id_seller']:
                if (article not in self.member_mapping and article['stock']>0):
                    self.list_article_widget.insertItem(index, "* %s - %s" % (
                        article['name'], article['stock']))
                    self.member_mapping.append(article)
                    index += 1

        self.list_article_widget.resize(self.list_article_widget.sizeHint())
        self.list_article_widget.move(0, 60)
        self.listlayout.addWidget(self.listwidget)
        self.layout.addLayout(self.listlayout)

    def update_list(self, id_article):
        print("update:")
        print(self.member_mapping)
        index = -1
        for i in range(0, len(self.member_mapping)):
            if(self.member_mapping[i]['id'] == id_article):
                index = i

        print(index)
        qitem = self.list_article_widget.item(index)
        item = qitem.text()
        tab = item.split("-")
        intv = int(tab[-1])-1
        if(intv > 0):
            string = tab[0]+ "- " + str(intv)
            print(string)
            qitem.setText(string)
        else:
            self.del_article()

    def add(self):
        try:
            #print(self.list_article_widget.currentRow())
            #print(self.member_mapping[self.list_article_widget.currentRow()]['id'])
            self.visiteur_controller.add_to_cart(self.member_mapping[self.list_article_widget.currentRow()]['name'], 1)
            self.update_list(self.member_mapping[self.list_article_widget.currentRow()]['id'])
        except:
            print("pas d'article sélectionné")

    def del_article(self):
        try:
            id_article = self.member_mapping[self.list_article_widget.currentRow()]['id']
            item = self.list_article_widget.takeItem(self.list_article_widget.currentRow())
            self.list_article_widget.removeItemWidget(item)
            self.seller_database.delete_article(id_article)
        except:
            print("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.valid_article_button.setText(_translate("MainWindow", "Ajouter au panier"))
