# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sokaradian\skrd\ESIEA\GLPOO\TP_GLPOO\list_seller_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from view.Visiteur import validation

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, visiteur_controller):
        self.visiteur_controller = visiteur_controller
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_article_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_article_widget.setGeometry(QtCore.QRect(80, 50, 201, 192))
        self.list_article_widget.setObjectName("list_article_widget")

        self.valid_article_button = QtWidgets.QPushButton(self.centralwidget)
        self.valid_article_button.setGeometry(QtCore.QRect(130, 270, 91, 23))
        self.valid_article_button.setObjectName("valid_article_button")
        self.valid_article_button.clicked.connect(self.validate_cart)
        self.valid_article_button.move(100,300)

        self.remove_article_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_article_button.setGeometry(QtCore.QRect(130, 270, 91, 23))
        self.remove_article_button.setObjectName("remove_article_button")
        self.remove_article_button.move(0,300)
        self.remove_article_button.clicked.connect(self.remove)

        self.listlayout = QtWidgets.QGridLayout()
        self.listwidget = QtWidgets.QListWidget()
        print("cart - half setup")
        self.member_mapping = {}
        self.layout = QtWidgets.QHBoxLayout()

        self.list(visiteur_controller)

        print("after list")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def list(self, seller_id):
        print("call")
        index = 0

        for article in self.visiteur_controller.show_cart():
            print(article[0])
            print(article[1])

            self.list_article_widget.insertItem(index, "* %s %d" % (
                article[0], article[1]))
            self.member_mapping[index] = article
            index += 1

        self.list_article_widget.resize(self.list_article_widget.sizeHint())
        self.list_article_widget.move(0, 60)
        self.listlayout.addWidget(self.listwidget)
        self.layout.addLayout(self.listlayout)

    def remove(self):
        self.visiteur_controller.remove_from_cart(self.member_mapping[self.list_article_widget.currentRow()]['name'], 1)
        #remove row
        self.list_article_widget.removeItemWidget(self.list_article_widget.currentItem())

    def validate_cart(self):
        self.visiteur_controller.validate_cart()
        #clear le panier
        self.list_article_widget.clear()
        #show small window "your command is validated
        self.test_w = QtWidgets.QWidget()
        self.ui_test = validation.Ui_MainWindow()
        self.ui_test.setupUi(self.test_w)
        self.test_w.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.valid_article_button.setText(_translate("MainWindow", "Valider le panier"))
        self.remove_article_button.setText(_translate("MainWindow", "Supprimer cet article"))
